// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// NOTE: The API keys below are standard, public identifiers embedded into the
/// compiled client application bundle. They do not need to be hidden or kept
/// secret, as Firebase security relies on Firestore Rules, Storage Rules, and
/// Firebase App Check rather than restricting key access.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHOqZTVq2f0MfBIOA-3EgNU0Wi-Mc9K4',
    appId: '1:336047914954:web:22ea16240855a2ab4ad933',
    messagingSenderId: '336047914954',
    projectId: 'sanad-depi-app',
    authDomain: 'sanad-depi-app.firebaseapp.com',
    storageBucket: 'sanad-depi-app.firebasestorage.app',
    measurementId: 'G-RRYTW44LRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmj0nHol8m9OIONegLGj9jQtT7Aka0tlY',
    appId: '1:336047914954:android:6dd6fd07f7b992cb4ad933',
    messagingSenderId: '336047914954',
    projectId: 'sanad-depi-app',
    storageBucket: 'sanad-depi-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LXcz4VTqaXrZpe1efObN466f1OgRzyY',
    appId: '1:336047914954:ios:b43d3988300f9ae24ad933',
    messagingSenderId: '336047914954',
    projectId: 'sanad-depi-app',
    storageBucket: 'sanad-depi-app.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LXcz4VTqaXrZpe1efObN466f1OgRzyY',
    appId: '1:336047914954:ios:b43d3988300f9ae24ad933',
    messagingSenderId: '336047914954',
    projectId: 'sanad-depi-app',
    storageBucket: 'sanad-depi-app.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHOqZTVq2f0MfBIOA-3EgNU0Wi-Mc9K4',
    appId: '1:336047914954:web:050e57227f2d1cd04ad933',
    messagingSenderId: '336047914954',
    projectId: 'sanad-depi-app',
    authDomain: 'sanad-depi-app.firebaseapp.com',
    storageBucket: 'sanad-depi-app.firebasestorage.app',
    measurementId: 'G-S9NP58MLTK',
  );
}
